package com.nibble.doyoulike.enums;

public enum Lifestyle {
    LIFESTYLE1_EARLY_BIRD,
    LIFESTYLE1_NIGHT_OWL,
    LIFESTYLE2_ACTIVE,
    LIFESTYLE2_FREQUENTLY_ABSENT,
    LIFESTYLE2_MOSTLY_ABSENT,
    LIFESTYLE3_SMOKE,
    LIFESTYLE3_DONT_SMOKE
}