package com.nibble.doyoulike.enums;

public enum Major {
    THEOLOGY,
    ENGLISH_STUDIES,
    BUSINESS_ADMINISTRATION,
    EARLY_CHILDHOOD_EDUCATION,
    GLOBAL_KOREAN_STUDIES,
    AVIATION_TOURISM_AND_FOREIGN_LANGUAGE,
    PHYSICAL_THERAPY,
    FOOD_AND_NUTRITION,
    SOCIAL_WELFARE,
    PUBLIC_HEALTH,
    COUNSELING_PSYCHOLOGY,
    LEISURE_AND_SPORTS_STUDIES,
    PHARMACY,
    NURSING,
    CHEMISTRY_AND_LIFE_SCIENCE,
    ENVIRONMENTAL_DESIGN_AND_HORTICULTURE,
    ANIMAL_LIFE_RESOURCES,
    INTEGRATIVE_BIOTECHNOLOGY,
    COMPUTER_SCIENCE_AND_ENGINEERING,
    AI_INFORMATICS,
    ARCHITECTURE,
    MUSIC,
    ART_AND_DESIGN,
    LIBERAL_ARTS
}